### ISSUE TITLE
missing done() is a bummer

### ISSUE THREAD

**Issue by vitaly-t** [tildeio/rsvp.js#373]
I've been working on my own library that's compatible with most of Promises/A+ implementations:

https://github.com/vitaly-t/pg-promise

And here's the result of running tests for compatibility that should give you an idea for a change ;)

* Promise - PASS;
* Bluebird - PASS;
* When - PASS;
* Q - PASS;
* RSVP - FAIL: missing method `done()`, have to replace with `finally()`
* Lie - FAIL: missing method `done()`, no alternative provided;

Never mind `Lie`, it lost its momentum, but you see that all major competitions have `done()` in their implementation, so it is fair to say you guys really should add it also.

**Comment by stefanpenner** [comment]
We don't have plans to add done. In the aplus thread on done you will see @wycats's thoughts on it. Specifically how it is an anti pattern

**Comment by vitaly-t** [comment]
Popular usage patterns make specs, not someone's subjective views.

And with the promises competition tightening up you are voting yourself out by ignoring what's popular ;)

**Comment by stefanpenner** [comment]
> And with the promises competition tightening up you are voting yourself out by ignoring what's popular ;)

popular !== good, the done pattern is IMHO an anti-pattern as it breaks the promise paradigm. 

feel free to review some of the discussion: https://github.com/promises-aplus/promises-spec/issues/43 It is clearly a topic with many different opinions. Since that discussion has ended, I have continued to write complex asynchronous code without the need or want of `done`. I have not dismissed this proposed feature lightly, rather I have experimented with the approach time and time again, but continue to arrive at the same conclusion.

**Comment by stefanpenner** [comment]
> RSVP - FAIL: missing method done(), have to replace with finally()

`finally` and `done` have different semantics. I am extremely interested in pushing `finally` forward, and hopefully eventually it will become part of the spec. I do not have the same feeling about `done`.

If you use-case, is cleanup, or ensuring something runs. Please use `finally` and promise libraries that do not implement it, should implement it.

**Comment by vitaly-t** [comment]
`Promise` is the only big player who doesn't have `finally()` implemented. They have the same arguments as yourself, just in the opposite direction :) And I'm just a user of these frameworks :)

**Comment by stefanpenner** [comment]
> They have the same arguments as yourself, just in the opposite direction

link to their issues on `finally`?

**Comment by vitaly-t** [comment]
no, can't find it, but i'm using the latest version of Promise, and `finally` isn't there, not even on to-do list.

**Comment by stefanpenner** [comment]
@vitaly-t they likely have valid concerns, I have several myself, especially around `finally` and `ctrl-c` of the process. I do not believe we have nailed these semantics down yet. But I believe we can, and should. Ultimately I believe my concerns with `finally` are solvable, but not with done.

**Comment by tbremer** [comment]
The thing I have really enjoyed and the reason I advocate for RSVP over other `Promise`s implimentations is that it doesn't put a lot of extra stuff around the [Promises/A+ spec](https://promisesaplus.com/) or it's [test suite](https://github.com/promises-aplus/promises-tests).

Just ¢.02

**Comment by vitaly-t** [comment]
@tbremer lots of extra stuff would signal that the spec wasn't good to begin with ;) I think we are missing some good usage tutorials to weight out every scenario and approach, case in point. I've been using promises for a while, but still find myself in the woods every so often, and I wonder why :)

**Comment by stefanpenner** [comment]
> ;) :)

you seem awfully happy 

> lots of extra stuff would signal that the spec wasn't good to begin with

the spec is rolling, I believe the initial release was solid. But will continue to be added to over time.
`finally` and reflection are likely good candidates for future iterations, they need champions but the committee feels positive.

**Comment by vitaly-t** [comment]
@stefanpenner, that's a few pints talking, after a long week, and I respect you standing by not making changes that you think don't make sense. As I user, I just would like to see the top libraries get their game together regarding the protocol.

**Comment by stefanpenner** [comment]
> As I user, I just would like to see the top libraries get their game together regarding the protocol.

lets figure out what the opposition to `finally` is, and try and solve it.

**Comment by vitaly-t** [comment]
kicking up some dirt: https://github.com/then/promise/issues/78

...to see what comes up :)

**Comment by ForbesLindesay** [comment]
Just for the record:

I/we have no objections to `.finally`, it's just that nobody's asked for it before, and it's not in any standards.  Generally then/Promise works on the principal that you must have a really strong argument for adding anything that's not in the spec.  That argument is pretty easy to make for `.done`, `.nodeify` and `.denodeify`.  It has not previously been made for `.finally`.  Ideally I would like to see a specification written up for `.finally` before implementing it, but I have wanted that functionality on a few occasions, so I can see that it may be justified as an addition.

**Comment by ForbesLindesay** [comment]
P.S. `.finally` and `.done` are completely orthogonal features.  `.done` makes sure errors are not silenced, `.finally` saves you duplicating code when you want to do the same thing for success and failure.

**Comment by stefanpenner** [comment]
@ForbesLindesay ya. They are totally orthogonal, but I believe people use done often by mistake. When they want finally.

A spec. Or proposal for a spec is a good does. I believe the async finally semantics are currently extremely broken. Just consider what happens if the use process.exits during one of these gaps, the async finally is not called. This results in leaking cleanup steps. The only solution seems to layer something else on-top. Which seems like a failure of the spec.

I believe this is also a problem with try / finally and generators or async await.  

If there is interest ( there seems to be ) I can start enumerating scenarios that can be used as the basis for a spec. I just likely need guidance as spec writing isn't something I am familiar with.

**Comment by ForbesLindesay** [comment]
I think the best bet would probably be to start an issue in the promises/A+ spec repo.  It's pretty friendly to people who aren't used to writing specs.

It's worth noting that finally is never more than a best effort.  e.g. consider what happens if the power cord is cut.  The other issue is that most platforms only let you do synchronous work when they are about to exit, which would be severely limiting when it comes to performing any cleanup.

**Comment by stefanpenner** [comment]
> It's worth noting that finally is never more than a best effort. e.g. consider what happens if the power cord is cut. The other issue is that most platforms only let you do synchronous work when they are about to exit, which would be severely limiting when it comes to performing any cleanup.

Ya, I believe these limitations need to be enumerated, and the scenarios that could be made to work and the ones that can not be made to work should be documented.

**Comment by vitaly-t** [comment]
So much talking about a perfect architecture, while it's being failing tests for 2 weeks now :(

**Comment by stefanpenner** [comment]
@vitaly-t it works, issue are a dep of the Bulls tooling. Just be obscenely busy. Will sort shortly

**Comment by vitaly-t** [comment]
Just so, on what's been discussed, Promise just added `finally()` to their midst ;)

https://github.com/then/promise/pull/80

Are you still on the fence for adding `done()`? :)

**Comment by stefanpenner** [comment]
Ya. `done`  is extremely unlikely to be added here
