### ISSUE TITLE
Error: no global: `self` or `global` found

### ISSUE THREAD

**Issue by burgons** [tildeio/rsvp.js#410]
Hi Guys

Any ideas about the error I'm getting:

Error Evaluating RSVP.js @ Line: 737
[ERROR] :  Error: no global: `self` or `global` found
[ERROR] :  File: RSVP.js
[ERROR] :  Line: 737
[ERROR] :  SourceId: <null>
[ERROR] :  Backtrace:
[ERROR] :   undefined

Cheers

**Comment by stefanpenner** [comment]
@burgons can you provide some more information, this isn't actionable.

* where are you running RSVP (os/runtime etc..)
* what version of RSVP
* a reproduction of the issue

**Comment by stefanpenner** [comment]
sorry, would love to help. But without ^ it is hard to debug. Will gladly debug if ^ is provided

**Comment by shama** [comment]
FYI, it looks like a platform check was added in `rsvp@3.0.19` (it didn't exist on or before `rsvp@3.0.18`):
```js
/* global self */
if (typeof self === 'object') {
  platform = self;

  /* global global */
} else if (typeof global === 'object') {
  platform = global;
} else {
  throw new Error('no global: `self` or `global` found');
}
```

Maybe this is a build system artifact? Because it doesn't look like `platform` is even being used.

We hit this error because we have a shared library that is used by web and mobile. The JS environment we are using on Android to consume that library doesn't have a `self` nor `global` but AFIAK, those globals are not required in order to use RSVP.

Seeing that RSVP isn't using that `platform` check, it would be nice to see a `3.x.x` release without it in the assets.

**Comment by bekzod** [comment]
I think `platform checks` has been removed in `4.x.x`, please check

**Comment by shama** [comment]
FWIW, we've been staying with `rsvp@3.x` as a polyfill as that is the version that ships with `ember@2.9` that we are stuck on. But looking at later ember 2.x releases it looks like RSVP gets bumped into 4.x. So maybe we don't have to worry about compatibility issues with the major version bump. I'll give `4.8.5` a try.

I appreciate your response @bekzod!
